language: python

notifications:
  email: false

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libhdf5-serial-dev 
    - pip install numpy
    - pip install h5py
    - pip install requests
    - pip install tables
    - pip install pytz
    - pip install tornado
    - git clone https://github.com/HDFGroup/hdf5-json.git
    - cd hdf5-json
    - python setup.py install
    - cd .. 

script:
    - python test/testall.py --unit
    - python server/app.py >app.out &
    - sleep 5
    - python test/testall.py --integ
