language: python

notifications:
  email: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"


install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libhdf5-serial-dev
    - pip uninstall numpy -y 
    - pip install numpy>=1.10.4
    - pip install h5py
    - pip install requests
    - pip install pytz
    - pip install tornado
    - pip install watchdog
    - git clone https://github.com/HDFGroup/hdf5-json.git
    - cd hdf5-json
    - python setup.py install
    - cd ..
    - pip install .

script:
    - PYTHONPATH="test/unit" python test/testall.py --unit --failslow
    - python h5serv >h5serv.out &
    - sleep 5
    - PYTHONPATH="test/integ" python test/testall.py --integ --failslow
